name: generate breakout svg

on:
  schedule:
    - cron: "0 0 * * *"   # 00:00 UTC
  workflow_dispatch:       # allow manual to "Run workflow"

jobs:
  generate-svg:
    permissions:
      contents: write       # Permission granted
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate SVG
        uses: cyprieng/github-breakout@v1
        with:
          github_username: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paddle_color: "#0b596a"
          ball_color: "#0b596a"
          bricks_colors: "#0b3c4c,#2a6b7c,#4f9bab,#83c8d6,#b9edf5"
          enable_ghost_bricks: false

      - name: Move generated SVGs
        run: |
          mkdir -p images
          mv output/custom.svg images/breakout.svg

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push SVGs
        run: |
          git add images/breakout.svg
          git commit -m "chore: update breakout SVG" || echo "No changes to commit"
          git push
