name: generate breakout svg

on:
  schedule:
    - cron: "0 0 * * *"   # 00:00 UTC
  workflow_dispatch:       # allow manual to "Run workflow"

jobs:
  generate-svg:
    permissions:
      contents: write       # Permission granted
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate SVG
        uses: cyprieng/github-breakout@v1
        with:
          github_username: ${{ github.repository_owner }}
          paddle_color: "#3492eb"
          ball_color: "#3492eb"
          bricks_colors: "#cfe8fc,#8ec7f7,#5daaf2,#3492eb,#1f5fa8"
          enable_ghost_bricks: true

      - name: Move generated SVGs
        run: |
          mkdir -p images
          mv output/light.svg images/breakout-light.svg
          mv output/dark.svg images/breakout-dark.svg

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push SVGs
        run: |
          git add images/breakout-light.svg images/breakout-dark.svg
          git commit -m "chore: update breakout SVGs" || echo "No changes to commit"
          git push
